#!/bin/bash
#
# lsp_cat - output a heading line containing $MAN_PN prior to the
#           actual content of a manual page.
#
# Copyright (C) 2024, Dirk Gouders
#
# This file is part of lsp.
#
# lsp is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 2 of the License, or (at your option) any later
# version.
#
# lsp is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# lsp. If not, see <https://www.gnu.org/licenses/>.
#

if [ "$MAN_PN" != "" ] ; then
    echo "<lsp-man-pn>$MAN_PN</lsp-man-pn>"
fi

exec cat
