#!/bin/bash
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# lsp_cat - output a heading line containing $MAN_PN prior to the
#           actual content of a manual page.
#
# Copyright (C) 2024-2025 Dirk Gouders
#

if [ "$MAN_PN" != "" ] ; then
    echo "<lsp-man-pn>$MAN_PN</lsp-man-pn>"
fi

exec cat
