.\"
.\" lsp - list pages (or least significant pager)
.\"
.\" Copyright (C) 2023, Dirk Gouders
.\"
.\" This file is part of lsp.
.\"
.\" lsp is free software: you can redistribute it and/or modify it under the
.\" terms of the GNU General Public License as published by the Free Software
.\" Foundation, either version 2 of the License, or (at your option) any later
.\" version.
.\"
.\" lsp is distributed in the hope that it will be useful, but WITHOUT ANY
.\" WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
.\" A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License along with
.\" lsp. If not, see <https://www.gnu.org/licenses/>.
.\"
.TH lsp-help 1 03/24/2023 "" "lsp online help"
.SH General Information
\fBlsp\fR lists file content in pages; the content can come from files on
disk and from standard input, e.g. manual pages.
.SH Interacting with \fBlsp\fR
.TS
tab(;);
cfI s.
General keys
_
.T&
cw(1i)|l.
\fBKeyboard / Mouse\fR;\fBAction\fR
_
q;T{
- Quit \fBlsp\fR.
.br
- Quit TOC mode.
.br
- Close this help.
T}
_
h;Show this online help.
_
.T&
cfI s.
Handling manual pages
_
.T&
cw(1i)|l.
\fBKeyboard / Mouse\fR;\fBAction\fR
_
TAB;go to next valid reference in the manual page
_
Shift-TAB;go to previous valid reference
_
ENTER;open current reference
_
a;T{
.ba
show apropos(1) buffer of all manual pages on the
.br
system
.br
(The above commands can then be used to visit those
.br
references.)
T}
_
.T&
c|l.
m;open another manual page
_
T;T{
TOC mode: toggle through three levels of a TOC
.br
(or folding) mode:
.br
1) Only content starting in column 1 is shown.
.br
2) Additionaly, content starting in column 4 is shown.
.br
3) Add content starting in column 8,
.br
but only if it is followed by a line with deeper
.br
indentation.
.br
This mode is left by pressing 'q' or ENTER to jump
.br
to the highlighted entry.
T}
_
.T&
cfI s.
Movement in files
_
.T&
c|l.
\fBKeyboard / Mouse\fR;\fBAction\fR
.T&
c|l.
_
b
Page up;backward one page
_
Key up;backward one line
_
ENTER
Key down;forward one line
_
f
Page down
SPACE;forward one page
_
T{
<
T};backward to first page
_
T{
>
T};forward to last page
_
C-l;In a search:
;bring the current match to the top of the page
_
.T&
cfI s.
Searching in files
_
.T&
c|l.
\fBKeyboard / Mouse\fR;\fBAction\fR
_
/;search forward for regular expression
_
?;search backward for regular expression
_
n;find next match
_
p;find previous match
_
.T&
cfI s.
Switching open files
_
.T&
c|l.
\fBKeyboard / Mouse\fR;\fBAction\fR
_
B;show list of open files for selection
_
ENTER;switch to selected file
_
T{
c
T};kill (close) active file
_
.T&
cfI s.
Toggling options
_
.T&
c|l.
\fBKeyboard / Mouse\fR;\fBAction\fR
_
-c;toggle chopping of lines that do not fit the current
;width of the screen.
_
<ESC>
-h;toggle highlighting of search matches
_
-i;toggle case sensitivity in searches
_
-n;toggle line numbering
_
-V;toggle verification of references
_
.TE
